language: node_js

node_js:
  - lts/*
  - stable

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm i -g greenkeeper-lockfile@1

install:
  - '[[ $TRAVIS_BRANCH == greenkeeper/* ]] && npm install || npm ci'

before_script:
  - npm prune
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

deploy:
  provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    branch: master
