language: node_js
deploy:
  on:
    branch: master
  provider: npm
  email: johngeorge.wright@gmail.com
  api_key:
    secure: ORI4IoEzIbvvpaGOeS/C3SrImvWmxTDdjGek4vlC0OO2yOyq+Msh6kn7VBTWRqEiUOzvlmu4Hm2ntMVOjtX4AVRLF+Y7V8RXDiP8hr5sp74GD2mLZX7DpBUij/Rf+An3y0ONvRF2eazJyu0TTcB5Am7UdtEVHQbQ8s5kRTfvubEABCGwDptH27QFrlH8E2EHBRItqcjMgHGylGPQa8OoYQaewol9c3y1aFh1pV2QQRBGGvArSjAIvRIUme4gSe3HFeVDmSoo3JUE/4ywTVMrYuEiMrwTvbnnqxtSPRYQsdFYlk3blGMxRgXhJgweZXlx8Edwl57Y07oalimMl2Maen9Z/i9H337P3gbD/Wa1px7xsYRw66a9Nt1bFCpQGFwUA6G3oQs5quNjXtWGF78L9tMr1ZT5d10mI6XToQrBnG8zDB/AAlKQn/tp7mFQm//g/0WeUYru+it/LSauonWF4nyY1Gl10eexRw4r6R/9RQDCPsAov6YDKIc5wefahc4s5sJxHOI+MJx6Sw8y9JBDIQ28AmZ3+GTb0YFGIsu83a3I6MZ4K2FSeDMovyH+ejHqLPGfSkZBM75Q/1LM5tCtv7pJGx04Lsvu07M7PwW3xEfjkBDDn5rghIl8Yp5hhKewDlSnKpWurXOq7w5IjUoc2NzMY8PceHXGpoRDnE3jKLE=
